name: Auto Release on Master

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Typecheck
        run: bun run typecheck

      - name: Build
        run: bun run build

      - name: Bump plugin version
        run: bun scripts/bump-version.js

      - name: Commit version bump
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add manifest.json
          git commit -m "chore: bump plugin version"
          git push

      - name: Install Stream Deck CLI
        run: bun add -g @elgato/cli

      - name: Package plugin
        run: |
          streamdeck package \
            --force \
            --output ./dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          files: dist/*.streamDeckPlugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
